//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intex_Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string id { get; set; }
        public string configDesc { get; set; }
        public string configVal { get; set; }
    }
}
