//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intex_Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public int page { get; set; }
        public int requestCount { get; set; }
    }
}
